# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
    runs-on: macos-13

    strategy:
      matrix:
        xcode: 
        - "15.0"

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Select ${{ matrix.xcode }}
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-select@05f94658217eb8575f0aabd3b95e702a47995d21
      uses: devbotsxyz/xcode-select@v1.1.0
      with:
        # Version to use (like '11.7', '12' or simply 'latest')
        version: ${{ matrix.xcode }} # optional, default is latest
        # Whether to select a beta release or not. Beta releases may not always be available.
        beta: false # optional, default is false

    - name: Get swift version
      run: swift --version # Swift 5.9

    - name: SPM Cache ${{ matrix.xcode }}
      uses: actions/cache@v3.2.6
      with:
        path: .build
        key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.xcode }}-spm-
      
    - name: Build ${{ matrix.xcode }}
      run: swift build -v
      
    - name: Run tests ${{ matrix.xcode }}
      run: swift test -v 2>&1 | xcpretty
